// SMILES AND PEOPLE
const allEmoj = {
  "smiles and people": [
    { unicode: "U+1F600", shortcode: ":grinning_face:" },
    { unicode: "U+1F603", shortcode: ":grinning_face_with_big_eyes:" },
    { unicode: "U+1F604", shortcode: ":grinning_face_with_smiling_eyes:" },
    { unicode: "U+1F601", shortcode: ":beaming_face_with_smiling_eyes:" },
    { unicode: "U+1F606", shortcode: ":grinning_squinting_face:" },
    { unicode: "U+1F605", shortcode: ":grinning_face_with_sweat:" },
    { unicode: "U+1F923", shortcode: ":rolling_on_the_floor_laughing:" },
    { unicode: "U+1F602", shortcode: ":face_with_tears_of_joy:" },
    { unicode: "U+1F642", shortcode: ":slightly_smiling_face:" },
    { unicode: "U+1F643", shortcode: ":upside_down_face:" },
    { unicode: "U+1FAE0", shortcode: ":melting_face:" },
    { unicode: "U+1F609", shortcode: ":winking_face:" },
    { unicode: "U+1F60A", shortcode: ":smiling_face_with_smiling_eyes:" },
    { unicode: "U+1F607", shortcode: ":smiling_face_with_halo:" },
    { unicode: "U+1F970", shortcode: ":smiling_face_with_hearts:" },
    { unicode: "U+1F60D", shortcode: ":smiling_face_with_heart_eyes:" },
    { unicode: "U+1F929", shortcode: ":star_struck:" },
    { unicode: "U+1F618", shortcode: ":face_blowing_a_kiss:" },
    { unicode: "U+1F617", shortcode: ":kissing_face:" },
    { unicode: "U+263A", shortcode: ":smiling_face:" },
    { unicode: "U+1F61A", shortcode: ":kissing_face_with_closed_eyes:" },
    { unicode: "U+1F619", shortcode: ":kissing_face_with_smiling_eyes:" },
    { unicode: "U+1F972", shortcode: ":smiling_face_with_tear:" },
    { unicode: "U+1F60B", shortcode: ":face_savoring_food:" },
    { unicode: "U+1F61B", shortcode: ":face_with_tongue:" },
    { unicode: "U+1F61C", shortcode: ":winking_face_with_tongue:" },
    { unicode: "U+1F92A", shortcode: ":zany_face:" },
    { unicode: "U+1F61D", shortcode: ":squinting_face_with_tongue:" },
    { unicode: "U+1F911", shortcode: ":money_mouth_face:" },
    { unicode: "U+1F917", shortcode: ":smiling_face_with_open_hands:" },
    { unicode: "U+1F92D", shortcode: ":face_with_hand_over_mouth:" },
    {
      unicode: "U+1FAE2",
      shortcode: ":face_with_open_eyes_and_hand_over_mouth:",
    },
    { unicode: "U+1FAE3", shortcode: ":face_with_peeking_eye:" },
    { unicode: "U+1F92B", shortcode: ":shushing_face:" },
    { unicode: "U+1F914", shortcode: ":thinking_face:" },
    { unicode: "U+1FAE1", shortcode: ":saluting_face:" },
    { unicode: "U+1F910", shortcode: ":zipper_mouth_face:" },
    { unicode: "U+1F928", shortcode: ":face_with_raised_eyebrow:" },
    { unicode: "U+1F610", shortcode: ":neutral_face:" },
    { unicode: "U+1F611", shortcode: ":expressionless_face:" },
    { unicode: "U+1F636", shortcode: ":face_without_mouth:" },
    { unicode: "U+1FAE5", shortcode: ":dotted_line_face:" },
    { unicode: "U+1F636 U+200D U+1F32B U+FE0F", shortcode: ":face_in_clouds:" },
    { unicode: "U+1F60F", shortcode: ":smirking_face:" },
    { unicode: "U+1F612", shortcode: ":unamused_face:" },
    { unicode: "U+1F644", shortcode: ":face_with_rolling_eyes:" },
    { unicode: "U+1F62C", shortcode: ":grimacing_face:" },
    { unicode: "U+1F62E U+200D U+1F4A8", shortcode: ":face_exhaling:" },
    { unicode: "U+1F925", shortcode: ":⊛_shaking_face:" },
    { unicode: "U+1F60C", shortcode: ":relieved_face:" },
    { unicode: "U+1F614", shortcode: ":pensive_face:" },
    { unicode: "U+1F62A", shortcode: ":sleepy_face:" },
    { unicode: "U+1F924", shortcode: ":drooling_face:" },
    { unicode: "U+1F634", shortcode: ":sleeping_face:" },
    { unicode: "U+1F637", shortcode: ":face_with_medical_mask:" },
    { unicode: "U+1F912", shortcode: ":face_with_thermometer:" },
    { unicode: "U+1F915", shortcode: ":face_with_head_bandage:" },
    { unicode: "U+1F922", shortcode: ":nauseated_face:" },
    { unicode: "U+1F92E", shortcode: ":face_vomiting:" },
    { unicode: "U+1F927", shortcode: ":sneezing_face:" },
    { unicode: "U+1F975", shortcode: ":hot_face:" },
    { unicode: "U+1F976", shortcode: ":cold_face:" },
    { unicode: "U+1F974", shortcode: ":woozy_face:" },
    { unicode: "U+1F635", shortcode: ":face_with_crossed_out_eyes:" },
    { unicode: "U+1F635 U+200D U+1F4AB", shortcode: ":face_with_spiral_eyes:" },
    { unicode: "U+1F92F", shortcode: ":exploding_head:" },
    { unicode: "U+1F920", shortcode: ":cowboy_hat_face:" },
    { unicode: "U+1F973", shortcode: ":partying_face:" },
    { unicode: "U+1F978", shortcode: ":disguised_face:" },
    { unicode: "U+1F60E", shortcode: ":smiling_face_with_sunglasses:" },
    { unicode: "U+1F913", shortcode: ":nerd_face:" },
    { unicode: "U+1F9D0", shortcode: ":face_with_monocle:" },
    { unicode: "U+1F615", shortcode: ":confused_face:" },
    { unicode: "U+1FAE4", shortcode: ":face_with_diagonal_mouth:" },
    { unicode: "U+1F61F", shortcode: ":worried_face:" },
    { unicode: "U+1F641", shortcode: ":slightly_frowning_face:" },
    { unicode: "U+2639", shortcode: ":frowning_face:" },
    { unicode: "U+1F62E", shortcode: ":face_with_open_mouth:" },
    { unicode: "U+1F62F", shortcode: ":hushed_face:" },
    { unicode: "U+1F632", shortcode: ":astonished_face:" },
    { unicode: "U+1F633", shortcode: ":flushed_face:" },
    { unicode: "U+1F97A", shortcode: ":pleading_face:" },
    { unicode: "U+1F979", shortcode: ":face_holding_back_tears:" },
    { unicode: "U+1F626", shortcode: ":frowning_face_with_open_mouth:" },
    { unicode: "U+1F627", shortcode: ":anguished_face:" },
    { unicode: "U+1F628", shortcode: ":fearful_face:" },
    { unicode: "U+1F630", shortcode: ":anxious_face_with_sweat:" },
    { unicode: "U+1F625", shortcode: ":sad_but_relieved_face:" },
    { unicode: "U+1F622", shortcode: ":crying_face:" },
    { unicode: "U+1F62D", shortcode: ":loudly_crying_face:" },
    { unicode: "U+1F631", shortcode: ":face_screaming_in_fear:" },
    { unicode: "U+1F616", shortcode: ":confounded_face:" },
    { unicode: "U+1F623", shortcode: ":persevering_face:" },
    { unicode: "U+1F61E", shortcode: ":disappointed_face:" },
    { unicode: "U+1F613", shortcode: ":downcast_face_with_sweat:" },
    { unicode: "U+1F629", shortcode: ":weary_face:" },
    { unicode: "U+1F62B", shortcode: ":tired_face:" },
    { unicode: "U+1F971", shortcode: ":yawning_face:" },
    { unicode: "U+1F624", shortcode: ":face_with_steam_from_nose:" },
    { unicode: "U+1F621", shortcode: ":enraged_face:" },
    { unicode: "U+1F620", shortcode: ":angry_face:" },
    { unicode: "U+1F92C", shortcode: ":face_with_symbols_on_mouth:" },
    { unicode: "U+1F608", shortcode: ":smiling_face_with_horns:" },
    { unicode: "U+1F47F", shortcode: ":angry_face_with_horns:" },
    { unicode: "U+1F480", shortcode: ":skull:" },
    { unicode: "U+2620", shortcode: ":skull_and_crossbones:" },
    { unicode: "U+1F4A9", shortcode: ":pile_of_poo:" },
    { unicode: "U+1F921", shortcode: ":clown_face:" },
    { unicode: "U+1F479", shortcode: ":ogre:" },
    { unicode: "U+1F47A", shortcode: ":goblin:" },
    { unicode: "U+1F47B", shortcode: ":ghost:" },
    { unicode: "U+1F47D", shortcode: ":alien:" },
    { unicode: "U+1F47E", shortcode: ":alien_monster:" },
    { unicode: "U+1F916", shortcode: ":robot:" },
    { unicode: "U+1F63A", shortcode: ":grinning_cat:" },
    { unicode: "U+1F638", shortcode: ":grinning_cat_with_smiling_eyes:" },
    { unicode: "U+1F639", shortcode: ":cat_with_tears_of_joy:" },
    { unicode: "U+1F63B", shortcode: ":smiling_cat_with_heart_eyes:" },
    { unicode: "U+1F63C", shortcode: ":cat_with_wry_smile:" },
    { unicode: "U+1F63D", shortcode: ":kissing_cat:" },
    { unicode: "U+1F640", shortcode: ":weary_cat:" },
    { unicode: "U+1F63F", shortcode: ":crying_cat:" },
    { unicode: "U+1F63E", shortcode: ":pouting_cat:" },
    { unicode: "U+1F648", shortcode: ":see_no_evil_monkey:" },
    { unicode: "U+1F649", shortcode: ":hear_no_evil_monkey:" },
    { unicode: "U+1F64A", shortcode: ":speak_no_evil_monkey:" },
    { unicode: "U+1F48C", shortcode: ":love_letter:" },
    { unicode: "U+1F498", shortcode: ":heart_with_arrow:" },
    { unicode: "U+1F49D", shortcode: ":heart_with_ribbon:" },
    { unicode: "U+1F496", shortcode: ":sparkling_heart:" },
    { unicode: "U+1F497", shortcode: ":growing_heart:" },
    { unicode: "U+1F493", shortcode: ":beating_heart:" },
    { unicode: "U+1F49E", shortcode: ":revolving_hearts:" },
    { unicode: "U+1F495", shortcode: ":two_hearts:" },
    { unicode: "U+1F49F", shortcode: ":heart_decoration:" },
    { unicode: "U+2763", shortcode: ":heart_exclamation:" },
    { unicode: "U+1F494", shortcode: ":broken_heart:" },
    { unicode: "U+2764 U+FE0F U+200D U+1F525", shortcode: ":heart_on_fire:" },
    { unicode: "U+2764 U+FE0F U+200D U+1FA79", shortcode: ":mending_heart:" },
    { unicode: "U+2764", shortcode: ":⊛_pink_heart:" },
    { unicode: "U+1F9E1", shortcode: ":orange_heart:" },
    { unicode: "U+1F49B", shortcode: ":yellow_heart:" },
    { unicode: "U+1F49A", shortcode: ":green_heart:" },
    { unicode: "U+1F499", shortcode: ":blue_heart:" },
    { unicode: "U+1F49C", shortcode: ":purple_heart:" },
    { unicode: "U+1F90E", shortcode: ":brown_heart:" },
    { unicode: "U+1F5A4", shortcode: ":⊛_grey_heart:" },
    { unicode: "U+1F90D", shortcode: ":white_heart:" },
    { unicode: "U+1F48B", shortcode: ":kiss_mark:" },
    { unicode: "U+1F4AF", shortcode: ":hundred_points:" },
    { unicode: "U+1F4A2", shortcode: ":anger_symbol:" },
    { unicode: "U+1F4A5", shortcode: ":collision:" },
    { unicode: "U+1F4AB", shortcode: ":dizzy:" },
    { unicode: "U+1F4A6", shortcode: ":sweat_droplets:" },
    { unicode: "U+1F4A8", shortcode: ":dashing_away:" },
    { unicode: "U+1F573", shortcode: ":hole:" },
    { unicode: "U+1F4AC", shortcode: ":speech_balloon:" },
    {
      unicode: "U+1F441 U+FE0F U+200D U+1F5E8 U+FE0F",
      shortcode: ":eye_in_speech_bubble:",
    },
    { unicode: "U+1F5E8", shortcode: ":left_speech_bubble:" },
    { unicode: "U+1F5EF", shortcode: ":right_anger_bubble:" },
    { unicode: "U+1F4AD", shortcode: ":thought_balloon:" },
    { unicode: "U+1F4A4", shortcode: ":ZZZ:" },
    { unicode: "U+1F44B", shortcode: ":waving_hand:" },
    { unicode: "U+1F91A", shortcode: ":raised_back_of_hand:" },
    { unicode: "U+1F590", shortcode: ":hand_with_fingers_splayed:" },
    { unicode: "U+270B", shortcode: ":raised_hand:" },
    { unicode: "U+1F596", shortcode: ":vulcan_salute:" },
    { unicode: "U+1FAF1", shortcode: ":rightwards_hand:" },
    { unicode: "U+1FAF2", shortcode: ":leftwards_hand:" },
    { unicode: "U+1FAF3", shortcode: ":palm_down_hand:" },
    { unicode: "U+1FAF4", shortcode: ":⊛_rightwards_pushing_hand:" },
    { unicode: "U+1F44C", shortcode: ":OK_hand:" },
    { unicode: "U+1F90C", shortcode: ":pinched_fingers:" },
    { unicode: "U+1F90F", shortcode: ":pinching_hand:" },
    { unicode: "U+270C", shortcode: ":victory_hand:" },
    { unicode: "U+1F91E", shortcode: ":crossed_fingers:" },
    {
      unicode: "U+1FAF0",
      shortcode: ":hand_with_index_finger_and_thumb_crossed:",
    },
    { unicode: "U+1F91F", shortcode: ":love_you_gesture:" },
    { unicode: "U+1F918", shortcode: ":sign_of_the_horns:" },
    { unicode: "U+1F919", shortcode: ":call_me_hand:" },
    { unicode: "U+1F448", shortcode: ":backhand_index_pointing_left:" },
    { unicode: "U+1F449", shortcode: ":backhand_index_pointing_right:" },
    { unicode: "U+1F446", shortcode: ":backhand_index_pointing_up:" },
    { unicode: "U+1F595", shortcode: ":middle_finger:" },
    { unicode: "U+1F447", shortcode: ":backhand_index_pointing_down:" },
    { unicode: "U+261D", shortcode: ":index_pointing_up:" },
    { unicode: "U+1FAF5", shortcode: ":index_pointing_at_the_viewer:" },
    { unicode: "U+1F44D", shortcode: ":thumbs_up:" },
    { unicode: "U+1F44E", shortcode: ":thumbs_down:" },
    { unicode: "U+270A", shortcode: ":raised_fist:" },
    { unicode: "U+1F44A", shortcode: ":oncoming_fist:" },
    { unicode: "U+1F91B", shortcode: ":left_facing_fist:" },
    { unicode: "U+1F91C", shortcode: ":right_facing_fist:" },
    { unicode: "U+1F44F", shortcode: ":clapping_hands:" },
    { unicode: "U+1F64C", shortcode: ":raising_hands:" },
    { unicode: "U+1FAF6", shortcode: ":heart_hands:" },
    { unicode: "U+1F450", shortcode: ":open_hands:" },
    { unicode: "U+1F932", shortcode: ":palms_up_together:" },
    { unicode: "U+1F91D", shortcode: ":handshake:" },
    { unicode: "U+1F64F", shortcode: ":folded_hands:" },
    { unicode: "U+270D", shortcode: ":writing_hand:" },
    { unicode: "U+1F485", shortcode: ":nail_polish:" },
    { unicode: "U+1F933", shortcode: ":selfie:" },
    { unicode: "U+1F4AA", shortcode: ":flexed_biceps:" },
    { unicode: "U+1F9BE", shortcode: ":mechanical_arm:" },
    { unicode: "U+1F9BF", shortcode: ":mechanical_leg:" },
    { unicode: "U+1F9B5", shortcode: ":leg:" },
    { unicode: "U+1F9B6", shortcode: ":foot:" },
    { unicode: "U+1F442", shortcode: ":ear:" },
    { unicode: "U+1F9BB", shortcode: ":ear_with_hearing_aid:" },
    { unicode: "U+1F443", shortcode: ":nose:" },
    { unicode: "U+1F9E0", shortcode: ":brain:" },
    { unicode: "U+1FAC0", shortcode: ":anatomical_heart:" },
    { unicode: "U+1FAC1", shortcode: ":lungs:" },
    { unicode: "U+1F9B7", shortcode: ":tooth:" },
    { unicode: "U+1F9B4", shortcode: ":bone:" },
    { unicode: "U+1F440", shortcode: ":eyes:" },
    { unicode: "U+1F441", shortcode: ":eye:" },
    { unicode: "U+1F445", shortcode: ":tongue:" },
    { unicode: "U+1F444", shortcode: ":mouth:" },
    { unicode: "U+1FAE6", shortcode: ":biting_lip:" },
    { unicode: "U+1F476", shortcode: ":baby:" },
    { unicode: "U+1F9D2", shortcode: ":child:" },
    { unicode: "U+1F466", shortcode: ":boy:" },
    { unicode: "U+1F467", shortcode: ":girl:" },
    { unicode: "U+1F9D1", shortcode: ":person:" },
    { unicode: "U+1F471", shortcode: ":person_blond_hair:" },
    { unicode: "U+1F468", shortcode: ":man:" },
    { unicode: "U+1F9D4", shortcode: ":person_beard:" },
    { unicode: "U+1F9D4 U+200D U+2642 U+FE0F", shortcode: ":man_beard:" },
    { unicode: "U+1F9D4 U+200D U+2640 U+FE0F", shortcode: ":woman_beard:" },
    { unicode: "U+1F468 U+200D U+1F9B0", shortcode: ":man_red_hair:" },
    { unicode: "U+1F468 U+200D U+1F9B1", shortcode: ":man_curly_hair:" },
    { unicode: "U+1F468 U+200D U+1F9B3", shortcode: ":man_white_hair:" },
    { unicode: "U+1F468 U+200D U+1F9B2", shortcode: ":man_bald:" },
    { unicode: "U+1F469", shortcode: ":woman:" },
    { unicode: "U+1F469 U+200D U+1F9B0", shortcode: ":woman_red_hair:" },
    { unicode: "U+1F9D1 U+200D U+1F9B0", shortcode: ":person_red_hair:" },
    { unicode: "U+1F469 U+200D U+1F9B1", shortcode: ":woman_curly_hair:" },
    { unicode: "U+1F9D1 U+200D U+1F9B1", shortcode: ":person_curly_hair:" },
    { unicode: "U+1F469 U+200D U+1F9B3", shortcode: ":woman_white_hair:" },
    { unicode: "U+1F9D1 U+200D U+1F9B3", shortcode: ":person_white_hair:" },
    { unicode: "U+1F469 U+200D U+1F9B2", shortcode: ":woman_bald:" },
    { unicode: "U+1F9D1 U+200D U+1F9B2", shortcode: ":person_bald:" },
    {
      unicode: "U+1F471 U+200D U+2640 U+FE0F",
      shortcode: ":woman_blond_hair:",
    },
    { unicode: "U+1F471 U+200D U+2642 U+FE0F", shortcode: ":man_blond_hair:" },
    { unicode: "U+1F9D3", shortcode: ":older_person:" },
    { unicode: "U+1F474", shortcode: ":old_man:" },
    { unicode: "U+1F475", shortcode: ":old_woman:" },
    { unicode: "U+1F64D", shortcode: ":person_frowning:" },
    { unicode: "U+1F64D U+200D U+2642 U+FE0F", shortcode: ":man_frowning:" },
    { unicode: "U+1F64D U+200D U+2640 U+FE0F", shortcode: ":woman_frowning:" },
    { unicode: "U+1F64E", shortcode: ":person_pouting:" },
    { unicode: "U+1F64E U+200D U+2642 U+FE0F", shortcode: ":man_pouting:" },
    { unicode: "U+1F64E U+200D U+2640 U+FE0F", shortcode: ":woman_pouting:" },
    { unicode: "U+1F645", shortcode: ":person_gesturing_NO:" },
    {
      unicode: "U+1F645 U+200D U+2642 U+FE0F",
      shortcode: ":man_gesturing_NO:",
    },
    {
      unicode: "U+1F645 U+200D U+2640 U+FE0F",
      shortcode: ":woman_gesturing_NO:",
    },
    { unicode: "U+1F646", shortcode: ":person_gesturing_OK:" },
    {
      unicode: "U+1F646 U+200D U+2642 U+FE0F",
      shortcode: ":man_gesturing_OK:",
    },
    {
      unicode: "U+1F646 U+200D U+2640 U+FE0F",
      shortcode: ":woman_gesturing_OK:",
    },
    { unicode: "U+1F481", shortcode: ":person_tipping_hand:" },
    {
      unicode: "U+1F481 U+200D U+2642 U+FE0F",
      shortcode: ":man_tipping_hand:",
    },
    {
      unicode: "U+1F481 U+200D U+2640 U+FE0F",
      shortcode: ":woman_tipping_hand:",
    },
    { unicode: "U+1F64B", shortcode: ":person_raising_hand:" },
    {
      unicode: "U+1F64B U+200D U+2642 U+FE0F",
      shortcode: ":man_raising_hand:",
    },
    {
      unicode: "U+1F64B U+200D U+2640 U+FE0F",
      shortcode: ":woman_raising_hand:",
    },
    { unicode: "U+1F9CF", shortcode: ":deaf_person:" },
    { unicode: "U+1F9CF U+200D U+2642 U+FE0F", shortcode: ":deaf_man:" },
    { unicode: "U+1F9CF U+200D U+2640 U+FE0F", shortcode: ":deaf_woman:" },
    { unicode: "U+1F647", shortcode: ":person_bowing:" },
    { unicode: "U+1F647 U+200D U+2642 U+FE0F", shortcode: ":man_bowing:" },
    { unicode: "U+1F647 U+200D U+2640 U+FE0F", shortcode: ":woman_bowing:" },
    { unicode: "U+1F926", shortcode: ":person_facepalming:" },
    { unicode: "U+1F926 U+200D U+2642 U+FE0F", shortcode: ":man_facepalming:" },
    {
      unicode: "U+1F926 U+200D U+2640 U+FE0F",
      shortcode: ":woman_facepalming:",
    },
    { unicode: "U+1F937", shortcode: ":person_shrugging:" },
    { unicode: "U+1F937 U+200D U+2642 U+FE0F", shortcode: ":man_shrugging:" },
    { unicode: "U+1F937 U+200D U+2640 U+FE0F", shortcode: ":woman_shrugging:" },
    { unicode: "U+1F9D1 U+200D U+2695 U+FE0F", shortcode: ":health_worker:" },
    {
      unicode: "U+1F468 U+200D U+2695 U+FE0F",
      shortcode: ":man_health_worker:",
    },
    {
      unicode: "U+1F469 U+200D U+2695 U+FE0F",
      shortcode: ":woman_health_worker:",
    },
    { unicode: "U+1F9D1 U+200D U+1F393", shortcode: ":student:" },
    { unicode: "U+1F468 U+200D U+1F393", shortcode: ":man_student:" },
    { unicode: "U+1F469 U+200D U+1F393", shortcode: ":woman_student:" },
    { unicode: "U+1F9D1 U+200D U+1F3EB", shortcode: ":teacher:" },
    { unicode: "U+1F468 U+200D U+1F3EB", shortcode: ":man_teacher:" },
    { unicode: "U+1F469 U+200D U+1F3EB", shortcode: ":woman_teacher:" },
    { unicode: "U+1F9D1 U+200D U+2696 U+FE0F", shortcode: ":judge:" },
    { unicode: "U+1F468 U+200D U+2696 U+FE0F", shortcode: ":man_judge:" },
    { unicode: "U+1F469 U+200D U+2696 U+FE0F", shortcode: ":woman_judge:" },
    { unicode: "U+1F9D1 U+200D U+1F33E", shortcode: ":farmer:" },
    { unicode: "U+1F468 U+200D U+1F33E", shortcode: ":man_farmer:" },
    { unicode: "U+1F469 U+200D U+1F33E", shortcode: ":woman_farmer:" },
    { unicode: "U+1F9D1 U+200D U+1F373", shortcode: ":cook:" },
    { unicode: "U+1F468 U+200D U+1F373", shortcode: ":man_cook:" },
    { unicode: "U+1F469 U+200D U+1F373", shortcode: ":woman_cook:" },
    { unicode: "U+1F9D1 U+200D U+1F527", shortcode: ":mechanic:" },
    { unicode: "U+1F468 U+200D U+1F527", shortcode: ":man_mechanic:" },
    { unicode: "U+1F469 U+200D U+1F527", shortcode: ":woman_mechanic:" },
    { unicode: "U+1F9D1 U+200D U+1F3ED", shortcode: ":factory_worker:" },
    { unicode: "U+1F468 U+200D U+1F3ED", shortcode: ":man_factory_worker:" },
    { unicode: "U+1F469 U+200D U+1F3ED", shortcode: ":woman_factory_worker:" },
    { unicode: "U+1F9D1 U+200D U+1F4BC", shortcode: ":office_worker:" },
    { unicode: "U+1F468 U+200D U+1F4BC", shortcode: ":man_office_worker:" },
    { unicode: "U+1F469 U+200D U+1F4BC", shortcode: ":woman_office_worker:" },
    { unicode: "U+1F9D1 U+200D U+1F52C", shortcode: ":scientist:" },
    { unicode: "U+1F468 U+200D U+1F52C", shortcode: ":man_scientist:" },
    { unicode: "U+1F469 U+200D U+1F52C", shortcode: ":woman_scientist:" },
    { unicode: "U+1F9D1 U+200D U+1F4BB", shortcode: ":technologist:" },
    { unicode: "U+1F468 U+200D U+1F4BB", shortcode: ":man_technologist:" },
    { unicode: "U+1F469 U+200D U+1F4BB", shortcode: ":woman_technologist:" },
    { unicode: "U+1F9D1 U+200D U+1F3A4", shortcode: ":singer:" },
    { unicode: "U+1F468 U+200D U+1F3A4", shortcode: ":man_singer:" },
    { unicode: "U+1F469 U+200D U+1F3A4", shortcode: ":woman_singer:" },
    { unicode: "U+1F9D1 U+200D U+1F3A8", shortcode: ":artist:" },
    { unicode: "U+1F468 U+200D U+1F3A8", shortcode: ":man_artist:" },
    { unicode: "U+1F469 U+200D U+1F3A8", shortcode: ":woman_artist:" },
    { unicode: "U+1F9D1 U+200D U+2708 U+FE0F", shortcode: ":pilot:" },
    { unicode: "U+1F468 U+200D U+2708 U+FE0F", shortcode: ":man_pilot:" },
    { unicode: "U+1F469 U+200D U+2708 U+FE0F", shortcode: ":woman_pilot:" },
    { unicode: "U+1F9D1 U+200D U+1F680", shortcode: ":astronaut:" },
    { unicode: "U+1F468 U+200D U+1F680", shortcode: ":man_astronaut:" },
    { unicode: "U+1F469 U+200D U+1F680", shortcode: ":woman_astronaut:" },
    { unicode: "U+1F9D1 U+200D U+1F692", shortcode: ":firefighter:" },
    { unicode: "U+1F468 U+200D U+1F692", shortcode: ":man_firefighter:" },
    { unicode: "U+1F469 U+200D U+1F692", shortcode: ":woman_firefighter:" },
    { unicode: "U+1F46E", shortcode: ":police_officer:" },
    {
      unicode: "U+1F46E U+200D U+2642 U+FE0F",
      shortcode: ":man_police_officer:",
    },
    {
      unicode: "U+1F46E U+200D U+2640 U+FE0F",
      shortcode: ":woman_police_officer:",
    },
    { unicode: "U+1F575", shortcode: ":detective:" },
    {
      unicode: "U+1F575 U+FE0F U+200D U+2642 U+FE0F",
      shortcode: ":man_detective:",
    },
    {
      unicode: "U+1F575 U+FE0F U+200D U+2640 U+FE0F",
      shortcode: ":woman_detective:",
    },
    { unicode: "U+1F482", shortcode: ":guard:" },
    { unicode: "U+1F482 U+200D U+2642 U+FE0F", shortcode: ":man_guard:" },
    { unicode: "U+1F482 U+200D U+2640 U+FE0F", shortcode: ":woman_guard:" },
    { unicode: "U+1F977", shortcode: ":ninja:" },
    { unicode: "U+1F477", shortcode: ":construction_worker:" },
    { unicode: "U+1F477 U+200D U+2642 U+FE0F", shortcode: ":man:" },
    {
      unicode: "U+1F477 U+200D U+2640 U+FE0F",
      shortcode: ":woman_construction_worker:",
    },
    { unicode: "U+1FAC5", shortcode: ":person_with_crown:" },
    { unicode: "U+1F934", shortcode: ":prince:" },
    { unicode: "U+1F478", shortcode: ":princess:" },
    { unicode: "U+1F473", shortcode: ":person_wearing_turban:" },
    {
      unicode: "U+1F473 U+200D U+2642 U+FE0F",
      shortcode: ":man_wearing_turban:",
    },
    {
      unicode: "U+1F473 U+200D U+2640 U+FE0F",
      shortcode: ":woman_wearing_turban:",
    },
    { unicode: "U+1F472", shortcode: ":person_with_skullcap:" },
    { unicode: "U+1F9D5", shortcode: ":woman_with_headscarf:" },
    { unicode: "U+1F935", shortcode: ":person_in_tuxedo:" },
    { unicode: "U+1F935 U+200D U+2642 U+FE0F", shortcode: ":man_in_tuxedo:" },
    { unicode: "U+1F935 U+200D U+2640 U+FE0F", shortcode: ":woman_in_tuxedo:" },
    { unicode: "U+1F470", shortcode: ":person_with_veil:" },
    { unicode: "U+1F470 U+200D U+2642 U+FE0F", shortcode: ":man_with_veil:" },
    { unicode: "U+1F470 U+200D U+2640 U+FE0F", shortcode: ":woman_with_veil:" },
    { unicode: "U+1F930", shortcode: ":pregnant_woman:" },
    { unicode: "U+1FAC3", shortcode: ":pregnant_man:" },
    { unicode: "U+1FAC4", shortcode: ":pregnant_person:" },
    { unicode: "U+1F931", shortcode: ":breast_feeding:" },
    { unicode: "U+1F469 U+200D U+1F37C", shortcode: ":woman_feeding_baby:" },
    { unicode: "U+1F468 U+200D U+1F37C", shortcode: ":man_feeding_baby:" },
    { unicode: "U+1F9D1 U+200D U+1F37C", shortcode: ":person_feeding_baby:" },
    { unicode: "U+1F47C", shortcode: ":baby_angel:" },
    { unicode: "U+1F385", shortcode: ":Santa_Claus:" },
    { unicode: "U+1F936", shortcode: ":Mrs._Claus:" },
    { unicode: "U+1F9D1 U+200D U+1F384", shortcode: ":mx_claus:" },
    { unicode: "U+1F9B8", shortcode: ":superhero:" },
    { unicode: "U+1F9B8 U+200D U+2642 U+FE0F", shortcode: ":man_superhero:" },
    { unicode: "U+1F9B8 U+200D U+2640 U+FE0F", shortcode: ":woman_superhero:" },
    { unicode: "U+1F9B9", shortcode: ":supervillain:" },
    {
      unicode: "U+1F9B9 U+200D U+2642 U+FE0F",
      shortcode: ":man_supervillain:",
    },
    {
      unicode: "U+1F9B9 U+200D U+2640 U+FE0F",
      shortcode: ":woman_supervillain:",
    },
    { unicode: "U+1F9D9", shortcode: ":mage:" },
    { unicode: "U+1F9D9 U+200D U+2642 U+FE0F", shortcode: ":man_mage:" },
    { unicode: "U+1F9D9 U+200D U+2640 U+FE0F", shortcode: ":woman_mage:" },
    { unicode: "U+1F9DA", shortcode: ":fairy:" },
    { unicode: "U+1F9DA U+200D U+2642 U+FE0F", shortcode: ":man_fairy:" },
    { unicode: "U+1F9DA U+200D U+2640 U+FE0F", shortcode: ":woman_fairy:" },
    { unicode: "U+1F9DB", shortcode: ":vampire:" },
    { unicode: "U+1F9DB U+200D U+2642 U+FE0F", shortcode: ":man_vampire:" },
    { unicode: "U+1F9DB U+200D U+2640 U+FE0F", shortcode: ":woman_vampire:" },
    { unicode: "U+1F9DC", shortcode: ":merperson:" },
    { unicode: "U+1F9DC U+200D U+2642 U+FE0F", shortcode: ":merman:" },
    { unicode: "U+1F9DC U+200D U+2640 U+FE0F", shortcode: ":mermaid:" },
    { unicode: "U+1F9DD", shortcode: ":elf:" },
    { unicode: "U+1F9DD U+200D U+2642 U+FE0F", shortcode: ":man_elf:" },
    { unicode: "U+1F9DD U+200D U+2640 U+FE0F", shortcode: ":woman_elf:" },
    { unicode: "U+1F9DE", shortcode: ":genie:" },
    { unicode: "U+1F9DE U+200D U+2642 U+FE0F", shortcode: ":man_genie:" },
    { unicode: "U+1F9DE U+200D U+2640 U+FE0F", shortcode: ":woman_genie:" },
    { unicode: "U+1F9DF", shortcode: ":zombie:" },
    { unicode: "U+1F9DF U+200D U+2642 U+FE0F", shortcode: ":man_zombie:" },
    { unicode: "U+1F9DF U+200D U+2640 U+FE0F", shortcode: ":woman_zombie:" },
    { unicode: "U+1F9CC", shortcode: ":troll:" },
    { unicode: "U+1F486", shortcode: ":person_getting_massage:" },
    {
      unicode: "U+1F486 U+200D U+2642 U+FE0F",
      shortcode: ":man_getting_massage:",
    },
    {
      unicode: "U+1F486 U+200D U+2640 U+FE0F",
      shortcode: ":woman_getting_massage:",
    },
    { unicode: "U+1F487", shortcode: ":person_getting_haircut:" },
    {
      unicode: "U+1F487 U+200D U+2642 U+FE0F",
      shortcode: ":man_getting_haircut:",
    },
    {
      unicode: "U+1F487 U+200D U+2640 U+FE0F",
      shortcode: ":woman_getting_haircut:",
    },
    { unicode: "U+1F6B6", shortcode: ":person_walking:" },
    { unicode: "U+1F6B6 U+200D U+2642 U+FE0F", shortcode: ":man_walking:" },
    { unicode: "U+1F6B6 U+200D U+2640 U+FE0F", shortcode: ":woman_walking:" },
    { unicode: "U+1F9CD", shortcode: ":person_standing:" },
    { unicode: "U+1F9CD U+200D U+2642 U+FE0F", shortcode: ":man_standing:" },
    { unicode: "U+1F9CD U+200D U+2640 U+FE0F", shortcode: ":woman_standing:" },
    { unicode: "U+1F9CE", shortcode: ":person_kneeling:" },
    { unicode: "U+1F9CE U+200D U+2642 U+FE0F", shortcode: ":man_kneeling:" },
    { unicode: "U+1F9CE U+200D U+2640 U+FE0F", shortcode: ":woman_kneeling:" },
    {
      unicode: "U+1F9D1 U+200D U+1F9AF",
      shortcode: ":person_with_white_cane:",
    },
    { unicode: "U+1F468 U+200D U+1F9AF", shortcode: ":man_with_white_cane:" },
    { unicode: "U+1F469 U+200D U+1F9AF", shortcode: ":woman_with_white_cane:" },
    {
      unicode: "U+1F9D1 U+200D U+1F9BC",
      shortcode: ":person_in_motorized_wheelchair:",
    },
    {
      unicode: "U+1F468 U+200D U+1F9BC",
      shortcode: ":man_in_motorized_wheelchair:",
    },
    {
      unicode: "U+1F469 U+200D U+1F9BC",
      shortcode: ":woman_in_motorized_wheelchair:",
    },
    {
      unicode: "U+1F9D1 U+200D U+1F9BD",
      shortcode: ":person_in_manual_wheelchair:",
    },
    {
      unicode: "U+1F468 U+200D U+1F9BD",
      shortcode: ":man_in_manual_wheelchair:",
    },
    {
      unicode: "U+1F469 U+200D U+1F9BD",
      shortcode: ":woman_in_manual_wheelchair:",
    },
    { unicode: "U+1F3C3", shortcode: ":person_running:" },
    { unicode: "U+1F3C3 U+200D U+2642 U+FE0F", shortcode: ":man_running:" },
    { unicode: "U+1F3C3 U+200D U+2640 U+FE0F", shortcode: ":woman_running:" },
    { unicode: "U+1F483", shortcode: ":woman_dancing:" },
    { unicode: "U+1F57A", shortcode: ":man_dancing:" },
    { unicode: "U+1F574", shortcode: ":person_in_suit_levitating:" },
    { unicode: "U+1F46F", shortcode: ":people_with_bunny_ears:" },
    {
      unicode: "U+1F46F U+200D U+2642 U+FE0F",
      shortcode: ":men_with_bunny_ears:",
    },
    {
      unicode: "U+1F46F U+200D U+2640 U+FE0F",
      shortcode: ":women_with_bunny_ears:",
    },
    { unicode: "U+1F9D6", shortcode: ":person_in_steamy_room:" },
    {
      unicode: "U+1F9D6 U+200D U+2642 U+FE0F",
      shortcode: ":man_in_steamy_room:",
    },
    {
      unicode: "U+1F9D6 U+200D U+2640 U+FE0F",
      shortcode: ":woman_in_steamy_room:",
    },
    { unicode: "U+1F9D7", shortcode: ":person_climbing:" },
    { unicode: "U+1F9D7 U+200D U+2642 U+FE0F", shortcode: ":man_climbing:" },
    { unicode: "U+1F9D7 U+200D U+2640 U+FE0F", shortcode: ":woman_climbing:" },
    { unicode: "U+1F93A", shortcode: ":person_fencing:" },
    { unicode: "U+1F3C7", shortcode: ":horse_racing:" },
    { unicode: "U+26F7", shortcode: ":skier:" },
    { unicode: "U+1F3C2", shortcode: ":snowboarder:" },
    { unicode: "U+1F3CC", shortcode: ":person_golfing:" },
    {
      unicode: "U+1F3CC U+FE0F U+200D U+2642 U+FE0F",
      shortcode: ":man_golfing:",
    },
    {
      unicode: "U+1F3CC U+FE0F U+200D U+2640 U+FE0F",
      shortcode: ":woman_golfing:",
    },
    { unicode: "U+1F3C4", shortcode: ":person_surfing:" },
    { unicode: "U+1F3C4 U+200D U+2642 U+FE0F", shortcode: ":man_surfing:" },
    { unicode: "U+1F3C4 U+200D U+2640 U+FE0F", shortcode: ":woman_surfing:" },
    { unicode: "U+1F6A3", shortcode: ":person_rowing_boat:" },
    { unicode: "U+1F6A3 U+200D U+2642 U+FE0F", shortcode: ":man_rowing_boat:" },
    {
      unicode: "U+1F6A3 U+200D U+2640 U+FE0F",
      shortcode: ":woman_rowing_boat:",
    },
    { unicode: "U+1F3CA", shortcode: ":person_swimming:" },
    { unicode: "U+1F3CA U+200D U+2642 U+FE0F", shortcode: ":man_swimming:" },
    { unicode: "U+1F3CA U+200D U+2640 U+FE0F", shortcode: ":woman_swimming:" },
    { unicode: "U+26F9", shortcode: ":person_bouncing_ball:" },
    {
      unicode: "U+26F9 U+FE0F U+200D U+2642 U+FE0F",
      shortcode: ":man_bouncing_ball:",
    },
    {
      unicode: "U+26F9 U+FE0F U+200D U+2640 U+FE0F",
      shortcode: ":woman_bouncing_ball:",
    },
    { unicode: "U+1F3CB", shortcode: ":person_lifting_weights:" },
    {
      unicode: "U+1F3CB U+FE0F U+200D U+2642 U+FE0F",
      shortcode: ":man_lifting_weights:",
    },
    {
      unicode: "U+1F3CB U+FE0F U+200D U+2640 U+FE0F",
      shortcode: ":woman_lifting_weights:",
    },
    { unicode: "U+1F6B4", shortcode: ":person_biking:" },
    { unicode: "U+1F6B4 U+200D U+2642 U+FE0F", shortcode: ":man_biking:" },
    { unicode: "U+1F6B4 U+200D U+2640 U+FE0F", shortcode: ":woman_biking:" },
    { unicode: "U+1F6B5", shortcode: ":person_mountain_biking:" },
    {
      unicode: "U+1F6B5 U+200D U+2642 U+FE0F",
      shortcode: ":man_mountain_biking:",
    },
    {
      unicode: "U+1F6B5 U+200D U+2640 U+FE0F",
      shortcode: ":woman_mountain_biking:",
    },
    { unicode: "U+1F938", shortcode: ":person_cartwheeling:" },
    {
      unicode: "U+1F938 U+200D U+2642 U+FE0F",
      shortcode: ":man_cartwheeling:",
    },
    {
      unicode: "U+1F938 U+200D U+2640 U+FE0F",
      shortcode: ":woman_cartwheeling:",
    },
    { unicode: "U+1F93C", shortcode: ":people_wrestling:" },
    { unicode: "U+1F93C U+200D U+2642 U+FE0F", shortcode: ":men_wrestling:" },
    { unicode: "U+1F93C U+200D U+2640 U+FE0F", shortcode: ":women_wrestling:" },
    { unicode: "U+1F93D", shortcode: ":person_playing_water_polo:" },
    {
      unicode: "U+1F93D U+200D U+2642 U+FE0F",
      shortcode: ":man_playing_water_polo:",
    },
    {
      unicode: "U+1F93D U+200D U+2640 U+FE0F",
      shortcode: ":woman_playing_water_polo:",
    },
    { unicode: "U+1F93E", shortcode: ":person_playing_handball:" },
    {
      unicode: "U+1F93E U+200D U+2642 U+FE0F",
      shortcode: ":man_playing_handball:",
    },
    { unicode: "U+1F93E U+200D U+2640 U+FE0F", shortcode: ":woman:" },
    { unicode: "U+1F939", shortcode: ":person_juggling:" },
    { unicode: "U+1F939 U+200D U+2642 U+FE0F", shortcode: ":man_juggling:" },
    { unicode: "U+1F939 U+200D U+2640 U+FE0F", shortcode: ":woman_juggling:" },
    { unicode: "U+1F9D8", shortcode: ":person_in_lotus_position:" },
    {
      unicode: "U+1F9D8 U+200D U+2642 U+FE0F",
      shortcode: ":man_in_lotus_position:",
    },
    {
      unicode: "U+1F9D8 U+200D U+2640 U+FE0F",
      shortcode: ":woman_in_lotus_position:",
    },
    { unicode: "U+1F6C0", shortcode: ":person_taking_bath:" },
    { unicode: "U+1F6CC", shortcode: ":person_in_bed:" },
    {
      unicode: "U+1F9D1 U+200D U+1F91D U+200D U+1F9D1",
      shortcode: ":people_holding_hands:",
    },
    { unicode: "U+1F46D", shortcode: ":women_holding_hands:" },
    { unicode: "U+1F46B", shortcode: ":woman_and_man_holding_hands:" },
    { unicode: "U+1F46C", shortcode: ":men_holding_hands:" },
    { unicode: "U+1F48F", shortcode: ":kiss:" },
    {
      unicode: "U+1F469 U+200D U+2764 U+FE0F U+200D U+1F48B U+200D U+1F468",
      shortcode: ":kiss_woman_man:",
    },
    {
      unicode: "U+1F468 U+200D U+2764 U+FE0F U+200D U+1F48B U+200D U+1F468",
      shortcode: ":kiss_man_man:",
    },
    {
      unicode: "U+1F469 U+200D U+2764 U+FE0F U+200D U+1F48B U+200D U+1F469",
      shortcode: ":kiss_woman_woman:",
    },
    { unicode: "U+1F491", shortcode: ":couple_with_heart:" },
    {
      unicode: "U+1F469 U+200D U+2764 U+FE0F U+200D U+1F468",
      shortcode: ":couple_with_heart_woman_man:",
    },
    {
      unicode: "U+1F468 U+200D U+2764 U+FE0F U+200D U+1F468",
      shortcode: ":couple_with_heart_man_man:",
    },
    {
      unicode: "U+1F469 U+200D U+2764 U+FE0F U+200D U+1F469",
      shortcode: ":couple_with_heart_woman_woman:",
    },
    { unicode: "U+1F46A", shortcode: ":family:" },
    {
      unicode: "U+1F468 U+200D U+1F469 U+200D U+1F466",
      shortcode: ":family_man_woman_boy:",
    },
    {
      unicode: "U+1F468 U+200D U+1F469 U+200D U+1F467",
      shortcode: ":family_man_woman_girl:",
    },
    {
      unicode: "U+1F468 U+200D U+1F469 U+200D U+1F467 U+200D U+1F466",
      shortcode: ":family_man_woman_girl_boy:",
    },
    {
      unicode: "U+1F468 U+200D U+1F469 U+200D U+1F466 U+200D U+1F466",
      shortcode: ":family_man_woman_boy_boy:",
    },
    {
      unicode: "U+1F468 U+200D U+1F469 U+200D U+1F467 U+200D U+1F467",
      shortcode: ":family_man_woman_girl_girl:",
    },
    {
      unicode: "U+1F468 U+200D U+1F468 U+200D U+1F466",
      shortcode: ":family_man_man_boy:",
    },
    {
      unicode: "U+1F468 U+200D U+1F468 U+200D U+1F467",
      shortcode: ":family_man:",
    },
    {
      unicode: "U+1F468 U+200D U+1F468 U+200D U+1F467 U+200D U+1F466",
      shortcode: ":family_man_man_girl_boy:",
    },
    {
      unicode: "U+1F468 U+200D U+1F468 U+200D U+1F466 U+200D U+1F466",
      shortcode: ":family_man_man_boy_boy:",
    },
    {
      unicode: "U+1F468 U+200D U+1F468 U+200D U+1F467 U+200D U+1F467",
      shortcode: ":family_man_man_girl_girl:",
    },
    {
      unicode: "U+1F469 U+200D U+1F469 U+200D U+1F466",
      shortcode: ":family_woman_woman_boy:",
    },
    {
      unicode: "U+1F469 U+200D U+1F469 U+200D U+1F467",
      shortcode: ":family_woman_woman_girl:",
    },
    {
      unicode: "U+1F469 U+200D U+1F469 U+200D U+1F467 U+200D U+1F466",
      shortcode: ":family_woman_woman_girl_boy:",
    },
    {
      unicode: "U+1F469 U+200D U+1F469 U+200D U+1F466 U+200D U+1F466",
      shortcode: ":family_woman_woman_boy_boy:",
    },
    {
      unicode: "U+1F469 U+200D U+1F469 U+200D U+1F467 U+200D U+1F467",
      shortcode: ":family_woman_woman_girl_girl:",
    },
    { unicode: "U+1F468 U+200D U+1F466", shortcode: ":family_man_boy:" },
    {
      unicode: "U+1F468 U+200D U+1F466 U+200D U+1F466",
      shortcode: ":family_man_boy_boy:",
    },
    { unicode: "U+1F468 U+200D U+1F467", shortcode: ":family_man_girl:" },
    {
      unicode: "U+1F468 U+200D U+1F467 U+200D U+1F466",
      shortcode: ":family_man_girl_boy:",
    },
    {
      unicode: "U+1F468 U+200D U+1F467 U+200D U+1F467",
      shortcode: ":family_man_girl_girl:",
    },
    { unicode: "U+1F469 U+200D U+1F466", shortcode: ":family_woman_boy:" },
    {
      unicode: "U+1F469 U+200D U+1F466 U+200D U+1F466",
      shortcode: ":family_woman_boy_boy:",
    },
    { unicode: "U+1F469 U+200D U+1F467", shortcode: ":family_woman_girl:" },
    {
      unicode: "U+1F469 U+200D U+1F467 U+200D U+1F466",
      shortcode: ":family_woman_girl_boy:",
    },
    {
      unicode: "U+1F469 U+200D U+1F467 U+200D U+1F467",
      shortcode: ":family_woman_girl_girl:",
    },
    { unicode: "U+1F5E3", shortcode: ":speaking_head:" },
    { unicode: "U+1F464", shortcode: ":bust_in_silhouette:" },
    { unicode: "U+1F465", shortcode: ":busts_in_silhouette:" },
    { unicode: "U+1FAC2", shortcode: ":people_hugging:" },
    { unicode: "U+1F463", shortcode: ":footprints:" },
    { unicode: "U+1F9B0", shortcode: ":red_hair:" },
    { unicode: "U+1F9B1", shortcode: ":curly_hair:" },
    { unicode: "U+1F9B3", shortcode: ":white_hair:" },
    { unicode: "U+1F9B2", shortcode: ":bald:" },
  ],
  "aminals and nature": [
    { unicode: "U+1F435", shortcode: ":monkey_face:" },
    { unicode: "U+1F412", shortcode: ":monkey:" },
    { unicode: "U+1F98D", shortcode: ":gorilla:" },
    { unicode: "U+1F9A7", shortcode: ":orangutan:" },
    { unicode: "U+1F436", shortcode: ":dog_face:" },
    { unicode: "U+1F415", shortcode: ":dog:" },
    { unicode: "U+1F9AE", shortcode: ":guide_dog:" },
    { unicode: "U+1F415 U+200D U+1F9BA", shortcode: ":service_dog:" },
    { unicode: "U+1F429", shortcode: ":poodle:" },
    { unicode: "U+1F43A", shortcode: ":wolf:" },
    { unicode: "U+1F98A", shortcode: ":fox:" },
    { unicode: "U+1F99D", shortcode: ":raccoon:" },
    { unicode: "U+1F431", shortcode: ":cat_face:" },
    { unicode: "U+1F408", shortcode: ":cat:" },
    { unicode: "U+1F408 U+200D U+2B1B", shortcode: ":black_cat:" },
    { unicode: "U+1F981", shortcode: ":lion:" },
    { unicode: "U+1F42F", shortcode: ":tiger_face:" },
    { unicode: "U+1F405", shortcode: ":tiger:" },
    { unicode: "U+1F406", shortcode: ":leopard:" },
    { unicode: "U+1F434", shortcode: ":horse_face:" },
    { unicode: "U+1F40E", shortcode: ":horse:" },
    { unicode: "U+1F984", shortcode: ":unicorn:" },
    { unicode: "U+1F993", shortcode: ":zebra:" },
    { unicode: "U+1F98C", shortcode: ":deer:" },
    { unicode: "U+1F9AC", shortcode: ":bison:" },
    { unicode: "U+1F42E", shortcode: ":cow_face:" },
    { unicode: "U+1F402", shortcode: ":ox:" },
    { unicode: "U+1F403", shortcode: ":water_buffalo:" },
    { unicode: "U+1F404", shortcode: ":cow:" },
    { unicode: "U+1F437", shortcode: ":pig_face:" },
    { unicode: "U+1F416", shortcode: ":pig:" },
    { unicode: "U+1F417", shortcode: ":boar:" },
    { unicode: "U+1F43D", shortcode: ":pig_nose:" },
    { unicode: "U+1F40F", shortcode: ":ram:" },
    { unicode: "U+1F411", shortcode: ":ewe:" },
    { unicode: "U+1F410", shortcode: ":goat:" },
    { unicode: "U+1F42A", shortcode: ":camel:" },
    { unicode: "U+1F42B", shortcode: ":two_hump_camel:" },
    { unicode: "U+1F999", shortcode: ":llama:" },
    { unicode: "U+1F992", shortcode: ":giraffe:" },
    { unicode: "U+1F418", shortcode: ":elephant:" },
    { unicode: "U+1F9A3", shortcode: ":mammoth:" },
    { unicode: "U+1F98F", shortcode: ":rhinoceros:" },
    { unicode: "U+1F99B", shortcode: ":hippopotamus:" },
    { unicode: "U+1F42D", shortcode: ":mouse_face:" },
    { unicode: "U+1F401", shortcode: ":mouse:" },
    { unicode: "U+1F400", shortcode: ":rat:" },
    { unicode: "U+1F439", shortcode: ":hamster:" },
    { unicode: "U+1F430", shortcode: ":rabbit_face:" },
    { unicode: "U+1F407", shortcode: ":rabbit:" },
    { unicode: "U+1F43F", shortcode: ":chipmunk:" },
    { unicode: "U+1F9AB", shortcode: ":beaver:" },
    { unicode: "U+1F994", shortcode: ":hedgehog:" },
    { unicode: "U+1F987", shortcode: ":bat:" },
    { unicode: "U+1F43B", shortcode: ":bear:" },
    { unicode: "U+1F43B U+200D U+2744 U+FE0F", shortcode: ":polar_bear:" },
    { unicode: "U+1F428", shortcode: ":koala:" },
    { unicode: "U+1F43C", shortcode: ":panda:" },
    { unicode: "U+1F9A5", shortcode: ":sloth:" },
    { unicode: "U+1F9A6", shortcode: ":otter:" },
    { unicode: "U+1F9A8", shortcode: ":skunk:" },
    { unicode: "U+1F998", shortcode: ":kangaroo:" },
    { unicode: "U+1F9A1", shortcode: ":badger:" },
    { unicode: "U+1F43E", shortcode: ":paw_prints:" },
    { unicode: "U+1F983", shortcode: ":turkey:" },
    { unicode: "U+1F414", shortcode: ":chicken:" },
    { unicode: "U+1F413", shortcode: ":rooster:" },
    { unicode: "U+1F423", shortcode: ":hatching_chick:" },
    { unicode: "U+1F424", shortcode: ":baby_chick:" },
    { unicode: "U+1F425", shortcode: ":front_facing_baby_chick:" },
    { unicode: "U+1F426", shortcode: ":bird:" },
    { unicode: "U+1F427", shortcode: ":penguin:" },
    { unicode: "U+1F54A", shortcode: ":dove:" },
    { unicode: "U+1F985", shortcode: ":eagle:" },
    { unicode: "U+1F986", shortcode: ":duck:" },
    { unicode: "U+1F9A2", shortcode: ":swan:" },
    { unicode: "U+1F989", shortcode: ":owl:" },
    { unicode: "U+1F9A4", shortcode: ":dodo:" },
    { unicode: "U+1FAB6", shortcode: ":feather:" },
    { unicode: "U+1F9A9", shortcode: ":flamingo:" },
    { unicode: "U+1F99A", shortcode: ":peacock:" },
    { unicode: "U+1F99C", shortcode: ":parrot:" },
    { unicode: "U+1F438", shortcode: ":frog:" },
    { unicode: "U+1F40A", shortcode: ":crocodile:" },
    { unicode: "U+1F422", shortcode: ":turtle:" },
    { unicode: "U+1F98E", shortcode: ":lizard:" },
    { unicode: "U+1F40D", shortcode: ":snake:" },
    { unicode: "U+1F432", shortcode: ":dragon_face:" },
    { unicode: "U+1F409", shortcode: ":dragon:" },
    { unicode: "U+1F995", shortcode: ":sauropod:" },
    { unicode: "U+1F996", shortcode: ":t_rex:" },
    { unicode: "U+1F433", shortcode: ":spouting_whale:" },
    { unicode: "U+1F40B", shortcode: ":whale:" },
    { unicode: "U+1F42C", shortcode: ":dolphin:" },
    { unicode: "U+1F9AD", shortcode: ":seal:" },
    { unicode: "U+1F41F", shortcode: ":fish:" },
    { unicode: "U+1F420", shortcode: ":tropical_fish:" },
    { unicode: "U+1F421", shortcode: ":blowfish:" },
    { unicode: "U+1F988", shortcode: ":shark:" },
    { unicode: "U+1F419", shortcode: ":octopus:" },
    { unicode: "U+1F41A", shortcode: ":spiral_shell:" },
    { unicode: "U+1F40C", shortcode: ":snail:" },
    { unicode: "U+1F98B", shortcode: ":butterfly:" },
    { unicode: "U+1F41B", shortcode: ":bug:" },
    { unicode: "U+1F41C", shortcode: ":ant:" },
    { unicode: "U+1F41D", shortcode: ":honeybee:" },
    { unicode: "U+1FAB2", shortcode: ":beetle:" },
    { unicode: "U+1F41E", shortcode: ":lady_beetle:" },
    { unicode: "U+1F997", shortcode: ":cricket:" },
    { unicode: "U+1FAB3", shortcode: ":cockroach:" },
    { unicode: "U+1F577", shortcode: ":spider:" },
    { unicode: "U+1F578", shortcode: ":spider_web:" },
    { unicode: "U+1F982", shortcode: ":scorpion:" },
    { unicode: "U+1F99F", shortcode: ":mosquito:" },
    { unicode: "U+1FAB0", shortcode: ":fly:" },
    { unicode: "U+1FAB1", shortcode: ":worm:" },
    { unicode: "U+1F9A0", shortcode: ":microbe:" },
    { unicode: "U+1F490", shortcode: ":bouquet:" },
    { unicode: "U+1F338", shortcode: ":cherry_blossom:" },
    { unicode: "U+1F4AE", shortcode: ":white_flower:" },
    { unicode: "U+1FAB7", shortcode: ":lotus:" },
    { unicode: "U+1F3F5", shortcode: ":rosette:" },
    { unicode: "U+1F339", shortcode: ":rose:" },
    { unicode: "U+1F940", shortcode: ":wilted_flower:" },
    { unicode: "U+1F33A", shortcode: ":hibiscus:" },
    { unicode: "U+1F33B", shortcode: ":sunflower:" },
    { unicode: "U+1F33C", shortcode: ":blossom:" },
    { unicode: "U+1F337", shortcode: ":tulip:" },
    { unicode: "U+1F331", shortcode: ":seedling:" },
    { unicode: "U+1FAB4", shortcode: ":potted_plant:" },
    { unicode: "U+1F332", shortcode: ":evergreen_tree:" },
    { unicode: "U+1F333", shortcode: ":deciduous_tree:" },
    { unicode: "U+1F334", shortcode: ":palm_tree:" },
    { unicode: "U+1F335", shortcode: ":cactus:" },
    { unicode: "U+1F33E", shortcode: ":sheaf_of_rice:" },
    { unicode: "U+1F33F", shortcode: ":herb:" },
    { unicode: "U+2618", shortcode: ":shamrock:" },
    { unicode: "U+1F340", shortcode: ":four_leaf_clover:" },
    { unicode: "U+1F341", shortcode: ":maple_leaf:" },
    { unicode: "U+1F342", shortcode: ":fallen_leaf:" },
    { unicode: "U+1F343", shortcode: ":leaf_fluttering_in_wind:" },
    { unicode: "U+1FAB9", shortcode: ":empty_nest:" },
    { unicode: "U+1FABA", shortcode: ":nest_with_eggs:" },
    { unicode: "U+1F344", shortcode: ":mushroom:" },
  ],
  "travel and places": [
    { unicode: "U+1F30D", shortcode: ":globe_showing_europe_africa:" },
    { unicode: "U+1F30E", shortcode: ":globe_showing_americas:" },
    { unicode: "U+1F30F", shortcode: ":globe_showing_asia_australia:" },
    { unicode: "U+1F310", shortcode: ":globe_with_meridians:" },
    { unicode: "U+1F5FA", shortcode: ":world_map:" },
    { unicode: "U+1F5FE", shortcode: ":map_of_japan:" },
    { unicode: "U+1F9ED", shortcode: ":compass:" },
    { unicode: "U+1F3D4", shortcode: ":snow_capped_mountain:" },
    { unicode: "U+26F0", shortcode: ":mountain:" },
    { unicode: "U+1F30B", shortcode: ":volcano:" },
    { unicode: "U+1F5FB", shortcode: ":mount_fuji:" },
    { unicode: "U+1F3D5", shortcode: ":camping:" },
    { unicode: "U+1F3D6", shortcode: ":beach_with_umbrella:" },
    { unicode: "U+1F3DC", shortcode: ":desert:" },
    { unicode: "U+1F3DD", shortcode: ":desert_island:" },
    { unicode: "U+1F3DE", shortcode: ":national_park:" },
    { unicode: "U+1F3DF", shortcode: ":stadium:" },
    { unicode: "U+1F3DB", shortcode: ":classical_building:" },
    { unicode: "U+1F3D7", shortcode: ":building_construction:" },
    { unicode: "U+1F9F1", shortcode: ":brick:" },
    { unicode: "U+1FAA8", shortcode: ":rock:" },
    { unicode: "U+1FAB5", shortcode: ":wood:" },
    { unicode: "U+1F6D6", shortcode: ":hut:" },
    { unicode: "U+1F3D8", shortcode: ":houses:" },
    { unicode: "U+1F3DA", shortcode: ":derelict_house:" },
    { unicode: "U+1F3E0", shortcode: ":house:" },
    { unicode: "U+1F3E1", shortcode: ":house_with_garden:" },
    { unicode: "U+1F3E2", shortcode: ":office_building:" },
    { unicode: "U+1F3E3", shortcode: ":japanese_post_office:" },
    { unicode: "U+1F3E4", shortcode: ":post_office:" },
    { unicode: "U+1F3E5", shortcode: ":hospital:" },
    { unicode: "U+1F3E6", shortcode: ":bank:" },
    { unicode: "U+1F3E8", shortcode: ":hotel:" },
    { unicode: "U+1F3E9", shortcode: ":love_hotel:" },
    { unicode: "U+1F3EA", shortcode: ":convenience_store:" },
    { unicode: "U+1F3EB", shortcode: ":school:" },
    { unicode: "U+1F3EC", shortcode: ":department_store:" },
    { unicode: "U+1F3ED", shortcode: ":factory:" },
    { unicode: "U+1F3EF", shortcode: ":japanese_castle:" },
    { unicode: "U+1F3F0", shortcode: ":castle:" },
    { unicode: "U+1F492", shortcode: ":wedding:" },
    { unicode: "U+1F5FC", shortcode: ":tokyo_tower:" },
    { unicode: "U+1F5FD", shortcode: ":statue_of_liberty:" },
    { unicode: "U+26EA", shortcode: ":church:" },
    { unicode: "U+1F54C", shortcode: ":mosque:" },
    { unicode: "U+1F6D5", shortcode: ":hindu_temple:" },
    { unicode: "U+1F54D", shortcode: ":synagogue:" },
    { unicode: "U+26E9", shortcode: ":shinto_shrine:" },
    { unicode: "U+1F54B", shortcode: ":kaaba:" },
    { unicode: "U+26F2", shortcode: ":fountain:" },
    { unicode: "U+26FA", shortcode: ":tent:" },
    { unicode: "U+1F301", shortcode: ":foggy:" },
    { unicode: "U+1F303", shortcode: ":night_with_stars:" },
    { unicode: "U+1F3D9", shortcode: ":cityscape:" },
    { unicode: "U+1F304", shortcode: ":sunrise_over_mountains:" },
    { unicode: "U+1F305", shortcode: ":sunrise:" },
    { unicode: "U+1F306", shortcode: ":cityscape_at_dusk:" },
    { unicode: "U+1F307", shortcode: ":sunset:" },
    { unicode: "U+1F309", shortcode: ":bridge_at_night:" },
    { unicode: "U+2668", shortcode: ":hot_springs:" },
    { unicode: "U+1F3A0", shortcode: ":carousel_horse:" },
    { unicode: "U+1F6DD", shortcode: ":playground_slide:" },
    { unicode: "U+1F3A1", shortcode: ":ferris_wheel:" },
    { unicode: "U+1F3A2", shortcode: ":roller_coaster:" },
    { unicode: "U+1F488", shortcode: ":barber_pole:" },
    { unicode: "U+1F3AA", shortcode: ":circus_tent:" },
    { unicode: "U+1F682", shortcode: ":locomotive:" },
    { unicode: "U+1F683", shortcode: ":railway_car:" },
    { unicode: "U+1F684", shortcode: ":high_speed_train:" },
    { unicode: "U+1F685", shortcode: ":bullet_train:" },
    { unicode: "U+1F686", shortcode: ":train:" },
    { unicode: "U+1F687", shortcode: ":metro:" },
    { unicode: "U+1F688", shortcode: ":light_rail:" },
    { unicode: "U+1F689", shortcode: ":station:" },
    { unicode: "U+1F68A", shortcode: ":tram:" },
    { unicode: "U+1F69D", shortcode: ":monorail:" },
    { unicode: "U+1F69E", shortcode: ":mountain_railway:" },
    { unicode: "U+1F68B", shortcode: ":tram_car:" },
    { unicode: "U+1F68C", shortcode: ":bus:" },
    { unicode: "U+1F68D", shortcode: ":oncoming_bus:" },
    { unicode: "U+1F68E", shortcode: ":trolleybus:" },
    { unicode: "U+1F690", shortcode: ":minibus:" },
    { unicode: "U+1F691", shortcode: ":ambulance:" },
    { unicode: "U+1F692", shortcode: ":fire_engine:" },
    { unicode: "U+1F693", shortcode: ":police_car:" },
    { unicode: "U+1F694", shortcode: ":oncoming_police_car:" },
    { unicode: "U+1F695", shortcode: ":taxi:" },
    { unicode: "U+1F696", shortcode: ":oncoming_taxi:" },
    { unicode: "U+1F697", shortcode: ":automobile:" },
    { unicode: "U+1F698", shortcode: ":oncoming_automobile:" },
    { unicode: "U+1F699", shortcode: ":sport_utility_vehicle:" },
    { unicode: "U+1F6FB", shortcode: ":pickup_truck:" },
    { unicode: "U+1F69A", shortcode: ":delivery_truck:" },
    { unicode: "U+1F69B", shortcode: ":articulated_lorry:" },
    { unicode: "U+1F69C", shortcode: ":tractor:" },
    { unicode: "U+1F3CE", shortcode: ":racing_car:" },
    { unicode: "U+1F3CD", shortcode: ":motorcycle:" },
    { unicode: "U+1F6F5", shortcode: ":motor_scooter:" },
    { unicode: "U+1F9BD", shortcode: ":manual_wheelchair:" },
    { unicode: "U+1F9BC", shortcode: ":motorized_wheelchair:" },
    { unicode: "U+1F6FA", shortcode: ":auto_rickshaw:" },
    { unicode: "U+1F6B2", shortcode: ":bicycle:" },
    { unicode: "U+1F6F4", shortcode: ":kick_scooter:" },
    { unicode: "U+1F6F9", shortcode: ":skateboard:" },
    { unicode: "U+1F6FC", shortcode: ":roller_skate:" },
    { unicode: "U+1F68F", shortcode: ":bus_stop:" },
    { unicode: "U+1F6E3", shortcode: ":motorway:" },
    { unicode: "U+1F6E4", shortcode: ":railway_track:" },
    { unicode: "U+1F6E2", shortcode: ":oil_drum:" },
    { unicode: "U+26FD", shortcode: ":fuel_pump:" },
    { unicode: "U+1F6DE", shortcode: ":wheel:" },
    { unicode: "U+1F6A8", shortcode: ":police_car_light:" },
    { unicode: "U+1F6A5", shortcode: ":horizontal_traffic_light:" },
    { unicode: "U+1F6A6", shortcode: ":vertical_traffic_light:" },
    { unicode: "U+1F6D1", shortcode: ":stop_sign:" },
    { unicode: "U+1F6A7", shortcode: ":construction:" },
    { unicode: "U+2693", shortcode: ":anchor:" },
    { unicode: "U+1F6DF", shortcode: ":ring_buoy:" },
    { unicode: "U+26F5", shortcode: ":sailboat:" },
    { unicode: "U+1F6F6", shortcode: ":canoe:" },
    { unicode: "U+1F6A4", shortcode: ":speedboat:" },
    { unicode: "U+1F6F3", shortcode: ":passenger_ship:" },
    { unicode: "U+26F4", shortcode: ":ferry:" },
    { unicode: "U+1F6E5", shortcode: ":motor_boat:" },
    { unicode: "U+1F6A2", shortcode: ":ship:" },
    { unicode: "U+2708", shortcode: ":airplane:" },
    { unicode: "U+1F6E9", shortcode: ":small_airplane:" },
    { unicode: "U+1F6EB", shortcode: ":airplane_departure:" },
    { unicode: "U+1F6EC", shortcode: ":airplane_arrival:" },
    { unicode: "U+1FA82", shortcode: ":parachute:" },
    { unicode: "U+1F4BA", shortcode: ":seat:" },
    { unicode: "U+1F681", shortcode: ":helicopter:" },
    { unicode: "U+1F69F", shortcode: ":suspension_railway:" },
    { unicode: "U+1F6A0", shortcode: ":mountain_cableway:" },
    { unicode: "U+1F6A1", shortcode: ":aerial_tramway:" },
    { unicode: "U+1F6F0", shortcode: ":satellite:" },
    { unicode: "U+1F680", shortcode: ":rocket:" },
    { unicode: "U+1F6F8", shortcode: ":flying_saucer:" },
    { unicode: "U+1F9F3", shortcode: ":luggage:" },
    { unicode: "U+231B", shortcode: ":hourglass_done:" },
    { unicode: "U+23F3", shortcode: ":hourglass_not_done:" },
    { unicode: "U+231A", shortcode: ":watch:" },
    { unicode: "U+23F0", shortcode: ":alarm_clock:" },
    { unicode: "U+23F1", shortcode: ":stopwatch:" },
    { unicode: "U+23F2", shortcode: ":timer_clock:" },
    { unicode: "U+1F570", shortcode: ":mantelpiece_clock:" },
    { unicode: "U+1F55B", shortcode: ":twelve_oclock:" },
    { unicode: "U+1F567", shortcode: ":twelve_thirty:" },
    { unicode: "U+1F550", shortcode: ":one_oclock:" },
    { unicode: "U+1F55C", shortcode: ":one_thirty:" },
    { unicode: "U+1F551", shortcode: ":two_oclock:" },
    { unicode: "U+1F55D", shortcode: ":two_thirty:" },
    { unicode: "U+1F552", shortcode: ":three_oclock:" },
    { unicode: "U+1F55E", shortcode: ":three_thirty:" },
    { unicode: "U+1F553", shortcode: ":four_oclock:" },
    { unicode: "U+1F55F", shortcode: ":four_thirty:" },
    { unicode: "U+1F554", shortcode: ":five_oclock:" },
    { unicode: "U+1F560", shortcode: ":five_thirty:" },
    { unicode: "U+1F555", shortcode: ":six_oclock:" },
    { unicode: "U+1F561", shortcode: ":six_thirty:" },
    { unicode: "U+1F556", shortcode: ":seven_oclock:" },
    { unicode: "U+1F562", shortcode: ":seven_thirty:" },
    { unicode: "U+1F557", shortcode: ":eight_oclock:" },
    { unicode: "U+1F563", shortcode: ":eight_thirty:" },
    { unicode: "U+1F558", shortcode: ":nine_oclock:" },
    { unicode: "U+1F564", shortcode: ":nine_thirty:" },
    { unicode: "U+1F559", shortcode: ":ten_oclock:" },
    { unicode: "U+1F565", shortcode: ":ten_thirty:" },
    { unicode: "U+1F55A", shortcode: ":eleven_oclock:" },
    { unicode: "U+1F566", shortcode: ":eleven_thirty:" },
    { unicode: "U+1F311", shortcode: ":new_moon:" },
    { unicode: "U+1F312", shortcode: ":waxing_crescent_moon:" },
    { unicode: "U+1F313", shortcode: ":first_quarter_moon:" },
    { unicode: "U+1F314", shortcode: ":waxing_gibbous_moon:" },
    { unicode: "U+1F315", shortcode: ":full_moon:" },
    { unicode: "U+1F316", shortcode: ":waning_gibbous_moon:" },
    { unicode: "U+1F317", shortcode: ":last_quarter_moon:" },
    { unicode: "U+1F318", shortcode: ":waning_crescent_moon:" },
    { unicode: "U+1F319", shortcode: ":crescent_moon:" },
    { unicode: "U+1F31A", shortcode: ":new_moon_face:" },
    { unicode: "U+1F31B", shortcode: ":first_quarter_moon_face:" },
    { unicode: "U+1F31C", shortcode: ":last_quarter_moon_face:" },
    { unicode: "U+1F321", shortcode: ":thermometer:" },
    { unicode: "U+2600", shortcode: ":sun:" },
    { unicode: "U+1F31D", shortcode: ":full_moon_face:" },
    { unicode: "U+1F31E", shortcode: ":sun_with_face:" },
    { unicode: "U+1FA90", shortcode: ":ringed_planet:" },
    { unicode: "U+2B50", shortcode: ":star:" },
    { unicode: "U+1F31F", shortcode: ":glowing_star:" },
    { unicode: "U+1F320", shortcode: ":shooting_star:" },
    { unicode: "U+1F30C", shortcode: ":milky_way:" },
    { unicode: "U+2601", shortcode: ":cloud:" },
    { unicode: "U+26C5", shortcode: ":sun_behind_cloud:" },
    { unicode: "U+26C8", shortcode: ":cloud_with_lightning_and_rain:" },
    { unicode: "U+1F324", shortcode: ":sun_behind_small_cloud:" },
    { unicode: "U+1F325", shortcode: ":sun_behind_large_cloud:" },
    { unicode: "U+1F326", shortcode: ":sun_behind_rain_cloud:" },
    { unicode: "U+1F327", shortcode: ":cloud_with_rain:" },
    { unicode: "U+1F328", shortcode: ":cloud_with_snow:" },
    { unicode: "U+1F329", shortcode: ":cloud_with_lightning:" },
    { unicode: "U+1F32A", shortcode: ":tornado:" },
    { unicode: "U+1F32B", shortcode: ":fog:" },
    { unicode: "U+1F32C", shortcode: ":wind_face:" },
    { unicode: "U+1F300", shortcode: ":cyclone:" },
    { unicode: "U+1F308", shortcode: ":rainbow:" },
    { unicode: "U+1F302", shortcode: ":closed_umbrella:" },
    { unicode: "U+2602", shortcode: ":umbrella:" },
    { unicode: "U+2614", shortcode: ":umbrella_with_rain_drops:" },
    { unicode: "U+26F1", shortcode: ":umbrella_on_ground:" },
    { unicode: "U+26A1", shortcode: ":high_voltage:" },
    { unicode: "U+2744", shortcode: ":snowflake:" },
    { unicode: "U+2603", shortcode: ":snowman:" },
    { unicode: "U+26C4", shortcode: ":snowman_without_snow:" },
    { unicode: "U+2604", shortcode: ":comet:" },
    { unicode: "U+1F525", shortcode: ":fire:" },
    { unicode: "U+1F4A7", shortcode: ":droplet:" },
    { unicode: "U+1F30A", shortcode: ":water_wave:" },
  ],
  activities: [
    { unicode: "U+1F383", shortcode: ":jack_o_lantern:" },
    { unicode: "U+1F384", shortcode: ":christmas_tree:" },
    { unicode: "U+1F386", shortcode: ":fireworks:" },
    { unicode: "U+1F387", shortcode: ":sparkler:" },
    { unicode: "U+1F9E8", shortcode: ":firecracker:" },
    { unicode: "U+2728", shortcode: ":sparkles:" },
    { unicode: "U+1F388", shortcode: ":balloon:" },
    { unicode: "U+1F389", shortcode: ":party_popper:" },
    { unicode: "U+1F38A", shortcode: ":confetti_ball:" },
    { unicode: "U+1F38B", shortcode: ":tanabata_tree:" },
    { unicode: "U+1F38D", shortcode: ":pine_decoration:" },
    { unicode: "U+1F38E", shortcode: ":japanese_dolls:" },
    { unicode: "U+1F38F", shortcode: ":carp_streamer:" },
    { unicode: "U+1F390", shortcode: ":wind_chime:" },
    { unicode: "U+1F391", shortcode: ":moon_viewing_ceremony:" },
    { unicode: "U+1F9E7", shortcode: ":red_envelope:" },
    { unicode: "U+1F380", shortcode: ":ribbon:" },
    { unicode: "U+1F381", shortcode: ":wrapped_gift:" },
    { unicode: "U+1F397", shortcode: ":reminder_ribbon:" },
    { unicode: "U+1F39F", shortcode: ":admission_tickets:" },
    { unicode: "U+1F3AB", shortcode: ":ticket:" },
    { unicode: "U+1F396", shortcode: ":military_medal:" },
    { unicode: "U+1F3C6", shortcode: ":trophy:" },
    { unicode: "U+1F3C5", shortcode: ":sports_medal:" },
    { unicode: "U+1F947", shortcode: ":1st_place_medal:" },
    { unicode: "U+1F948", shortcode: ":2nd_place_medal:" },
    { unicode: "U+1F949", shortcode: ":3rd_place_medal:" },
    { unicode: "U+26BD", shortcode: ":soccer_ball:" },
    { unicode: "U+26BE", shortcode: ":baseball:" },
    { unicode: "U+1F94E", shortcode: ":softball:" },
    { unicode: "U+1F3C0", shortcode: ":basketball:" },
    { unicode: "U+1F3D0", shortcode: ":volleyball:" },
    { unicode: "U+1F3C8", shortcode: ":american_football:" },
    { unicode: "U+1F3C9", shortcode: ":rugby_football:" },
    { unicode: "U+1F3BE", shortcode: ":tennis:" },
    { unicode: "U+1F94F", shortcode: ":flying_disc:" },
    { unicode: "U+1F3B3", shortcode: ":bowling:" },
    { unicode: "U+1F3CF", shortcode: ":cricket_game:" },
    { unicode: "U+1F3D1", shortcode: ":field_hockey:" },
    { unicode: "U+1F3D2", shortcode: ":ice_hockey:" },
    { unicode: "U+1F94D", shortcode: ":lacrosse:" },
    { unicode: "U+1F3D3", shortcode: ":ping_pong:" },
    { unicode: "U+1F3F8", shortcode: ":badminton:" },
    { unicode: "U+1F94A", shortcode: ":boxing_glove:" },
    { unicode: "U+1F94B", shortcode: ":martial_arts_uniform:" },
    { unicode: "U+1F945", shortcode: ":goal_net:" },
    { unicode: "U+26F3", shortcode: ":flag_in_hole:" },
    { unicode: "U+26F8", shortcode: ":ice_skate:" },
    { unicode: "U+1F3A3", shortcode: ":fishing_pole:" },
    { unicode: "U+1F93F", shortcode: ":diving_mask:" },
    { unicode: "U+1F3BD", shortcode: ":running_shirt:" },
    { unicode: "U+1F3BF", shortcode: ":skis:" },
    { unicode: "U+1F6F7", shortcode: ":sled:" },
    { unicode: "U+1F94C", shortcode: ":curling_stone:" },
    { unicode: "U+1F3AF", shortcode: ":bullseye:" },
    { unicode: "U+1FA80", shortcode: ":yo_yo:" },
    { unicode: "U+1FA81", shortcode: ":kite:" },
    { unicode: "U+1F52B", shortcode: ":water_pistol:" },
    { unicode: "U+1F3B1", shortcode: ":pool_8_ball:" },
    { unicode: "U+1F52E", shortcode: ":crystal_ball:" },
    { unicode: "U+1FA84", shortcode: ":magic_wand:" },
    { unicode: "U+1F3AE", shortcode: ":video_game:" },
    { unicode: "U+1F579", shortcode: ":joystick:" },
    { unicode: "U+1F3B0", shortcode: ":slot_machine:" },
    { unicode: "U+1F3B2", shortcode: ":game_die:" },
    { unicode: "U+1F9E9", shortcode: ":puzzle_piece:" },
    { unicode: "U+1F9F8", shortcode: ":teddy_bear:" },
    { unicode: "U+1FA85", shortcode: ":piñata:" },
    { unicode: "U+1FAA9", shortcode: ":mirror_ball:" },
    { unicode: "U+1FA86", shortcode: ":nesting_dolls:" },
    { unicode: "U+2660", shortcode: ":spade_suit:" },
    { unicode: "U+2665", shortcode: ":heart_suit:" },
    { unicode: "U+2666", shortcode: ":diamond_suit:" },
    { unicode: "U+2663", shortcode: ":club_suit:" },
    { unicode: "U+265F", shortcode: ":chess_pawn:" },
    { unicode: "U+1F0CF", shortcode: ":joker:" },
    { unicode: "U+1F004", shortcode: ":mahjong_red_dragon:" },
    { unicode: "U+1F3B4", shortcode: ":flower_playing_cards:" },
    { unicode: "U+1F3AD", shortcode: ":performing_arts:" },
    { unicode: "U+1F5BC", shortcode: ":framed_picture:" },
    { unicode: "U+1F3A8", shortcode: ":artist_palette:" },
    { unicode: "U+1F9F5", shortcode: ":thread:" },
    { unicode: "U+1FAA1", shortcode: ":sewing_needle:" },
    { unicode: "U+1F9F6", shortcode: ":yarn:" },
    { unicode: "U+1FAA2", shortcode: ":knot:" },
  ],
};


module.exports = { allEmoj };
